image: node:alpine

variables:
  PUBLIC_URL: /gifted

cache:
  paths:
    - node_modules

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn test
  only:
    - master

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build --prod
    - cp public/index.html public/404.html
    - mv public _public
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - master
