image: "node:latest"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn test
  only:
    - master

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mkdir .public
    - cp -r build/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
    - master
